name: Maven CI (Java 21)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      runTests:
        description: "Run tests (true/false)"
        required: false
        default: "true"

# Prevent duplicate runs on the same branch/PR
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    services:
      dynamodb:
        image: amazon/dynamodb-local:1.21.0
        ports:
          - 8000:8000
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Show Java & Maven versions
        run: |
          java -version
          mvn -v
          

      - name: Wait for DynamoDB
        run: |
          sleep 30
          for i in {1..5}; do
            if curl -s --connect-timeout 3 http://localhost:8000/ >/dev/null 2>&1; then
              echo "DynamoDB Local ready"
              break
            fi
            sleep 5
          done

      - name: Build application
        run: mvn clean package -DskipTests

      - name: Run Payroll Job
        run: java -cp target/classes com.hrms.model.service.PayrollJob