name: Maven CI (Java 21)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Prevent duplicate runs on the same branch/PR
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Show Java & Maven versions
        run: |
          java -version
          mvn -v

      - name: Build & test with Maven
        run: mvn -B -ntp -U -e clean verify
        env:
          MAVEN_OPTS: "-Xmx2g"

      - name: Package (if not already packaged in verify)
        if: success()
        run: mvn -B -ntp -DskipTests package

      - name: Upload build artifacts (JARs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maven-artifacts
          path: |
            **/target/*.jar
            **/target/site/**
