name: Monthly Payroll Generation

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'  # Monthly at 00:00 UTC

jobs:
  build:
    name: Build Project
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: payroll-build
          path: target/*.jar

      - name: Upload Surefire Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/

  run-payroll:
    name: Run Payroll Job
    needs: build
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Payroll Job
        run: java -cp target/classes com.hrms.model.job.PayrollJob
