name: Monthly Payroll Generation

# Trigger: monthly schedule + manual run
on:
  schedule:
    - cron: '0 0 1 * *'   # 1st day of every month at midnight UTC
  workflow_dispatch:
    inputs:
      month:
        description: 'Month to generate payroll (optional)'
        required: false
        default: ''  # empty = current month

jobs:
  payroll:
    runs-on: windows-latest

    env:
      DB_URL: jdbc:mysql://localhost:3306/hrms_project
      DB_USER: root
      DB_PASSWORD: Aravind@123

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # Step 3: Clean target folder
      - name: Clean Project
        run: mvn clean

      # Step 4: Build Project (skip tests, safe shading)
      - name: Build Project
        run: mvn package "-Dmaven.test.skip=true"

      # Step 5: Run Payroll Job
      - name: Run Payroll Job
        run: |
          # Determine payroll month
          if ("%{{ github.event.inputs.month }}%"=="") (
            set PAYROLL_MONTH=%DATE:~4,2%
          ) else (
            set PAYROLL_MONTH=%{{ github.event.inputs.month }}%
          )
          echo Generating payroll for month: %PAYROLL_MONTH%
          # Run Payroll job and redirect all output to payroll.log
          java -cp target/hrms_project-1.0-SNAPSHOT-shaded.jar com.hrms.model.service.PayrollJobs %PAYROLL_MONTH% > payroll.log 2>&1

      # Step 6: Upload payroll log as artifact
      - name: Upload Payroll Log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: payroll-log
          path: payroll.log
