name: Payroll CI (Java 21)

on:
  workflow_dispatch:
    inputs:
      month:
        description: "Month to generate payroll (optional)"
        required: false
        default: ""

concurrency:
  group: payroll-${{ github.ref }}
  cancel-in-progress: true

jobs:
  payroll:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Aravind@123
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    env:
      DB_URL: jdbc:mysql://127.0.0.1:3306/hrms_project
      DB_USER: root
      DB_PASSWORD: Aravind@123
      CI: true

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Verify schema file exists
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing files:"
          ls -R
          if [ ! -f GitActionsdb/schema.sql ]; then
            echo "ERROR: GitActionsdb/schema.sql not found!"
            exit 1
          fi

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Show Java & Maven versions
        run: |
          java -version
          mvn -v

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..12}; do
            if mysql -h 127.0.0.1 -P 3306 -u $DB_USER -p$DB_PASSWORD -e "SELECT 1;" &> /dev/null; then
              echo "MySQL is ready."
              break
            else
              echo "Waiting for MySQL..."
              sleep 5
            fi
          done

      - name: Reset MySQL Database
        run: |
          echo "Resetting MySQL database..."
          mysql -h 127.0.0.1 -P 3306 -u $DB_USER -p$DB_PASSWORD -e "DROP DATABASE IF EXISTS hrms_project; CREATE DATABASE hrms_project;"

      - name: Initialize database schema
        run: |
          echo "Creating payrolls table from schema.sql..."
          mysql -h 127.0.0.1 -P 3306 -u $DB_USER -p$DB_PASSWORD hrms_project < GitActionsdb/schema.sql

      - name: Wait until payrolls table exists
        run: |
          echo "Waiting for payrolls table to exist..."
          for i in {1..12}; do
            TABLE_EXISTS=$(mysql -h 127.0.0.1 -P 3306 -u $DB_USER -p$DB_PASSWORD -D hrms_project -sse "SHOW TABLES LIKE 'payrolls';")
            if [ "$TABLE_EXISTS" == "payrolls" ]; then
              echo "Payrolls table exists."
              break
            else
              echo "Payrolls table not yet created, retrying..."
              sleep 5
            fi
          done

      - name: Build application
        run: mvn clean package -DskipTests

      - name: Run Payroll Job
        run: |
          PAYROLL_MONTH=${{ github.event.inputs.month }}
          if [ -z "$PAYROLL_MONTH" ]; then
            PAYROLL_MONTH=$(date +%m)
          fi
          echo "Generating payroll for month: $PAYROLL_MONTH"
          java -cp "target/classes:lib/mysql-connector-j-9.4.0.jar" com.hrms.model.service.PayrollJob $PAYROLL_MONTH > payroll.log 2>&1 || echo "Payroll job failed, see payroll.log"

      - name: Upload payroll log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: payroll-log
          path: payroll.log
