name: Auto Payroll Generation

# Trigger: 1st day of every month at 00:00 UTC or manual trigger
on:
  schedule:
    - cron: '0 0 1 * *'   # every 1st of the month at 00:00 UTC
  workflow_dispatch:

jobs:
  payroll:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: hrms_project
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DB_URL: jdbc:mysql://localhost:3306/hrms_project
      DB_USER: root
      DB_PASSWORD: Aravind@123

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h127.0.0.1 -P3306 --silent; then
              echo "MySQL is up!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Build & Run PayrollJob
        run: mvn clean package -DskipTests

      - name: Upload Payroll Log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: payroll-log
          path: payroll.log
