name: HRMS Full CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  build-test:
    name: Build & Test Payroll Project
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Maven Packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -B

      - name: Run Tests
        run: mvn test

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports
          path: target/surefire-reports/

  monthly-payroll:
    name: Monthly Payroll Generation
    runs-on: windows-latest
    needs: build-test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build Project
        run: mvn clean install -B

      - name: Generate Monthly Payroll
        run: java -cp target/hrms_project-1.0-SNAPSHOT.jar com.hrms.model.service.MonthlyPayrollJob

  qodana:
    name: Qodana Code Quality
    runs-on: windows-latest
    container:
      image: jetbrains/qodana-jvm:2025.1
    needs: build-test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Qodana Analysis
        run: qodana scan --save-report

      - name: Upload Qodana Report
        uses: actions/upload-artifact@v3
        with:
          name: qodana-report
          path: .qodana/report
