name: Monthly Payroll Generation

# Trigger: 1st day of every month at 00:00 UTC or manual trigger
on:
  schedule:
    - cron: '0 0 1 * *'   # monthly on 1st day at midnight UTC
  workflow_dispatch:       # allows manual runs

jobs:
  payroll:
    runs-on: windows-latest

    env:
      # Hardcoded local DB credentials (for private repo; not recommended for public repos)
      DB_URL: jdbc:mysql://localhost:3306/hrms_project
      DB_USER: root
      DB_PASSWORD: Aravind@123

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # Step 3: Build the project
      - name: Build Project
        run: mvn clean package -DskipTests

      # Step 4: Run PayrollJobs
      - name: Run Payroll Job
        run: java -cp target/hrms_project-1.0-SNAPSHOT-shaded.jar com.hrms.model.service.PayrollJobs

      # Step 5: Upload payroll log as artifact
      - name: Upload Payroll Log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: payroll-log
          path: payroll.log
