name: Monthly Payroll Generation


on:
  workflow_dispatch:
    inputs:
      month:
        description: 'Month to generate payroll (optional)'
        required: false
        default: ''


jobs:
  payroll:
    runs-on: windows-latest

    env:
      DB_URL: jdbc:mysql://localhost:3306/hrms_project
      DB_USER: root
      DB_PASSWORD: Aravind@123
      CI: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Reset MySQL Database
        shell: powershell
        run: |
          Write-Host "Resetting MySQL database..."
          mysql -u $env:DB_USER -p$env:DB_PASSWORD -e "DROP DATABASE IF EXISTS hrms_project; CREATE DATABASE hrms_project;"

      - name: Clean Project
        run: mvn clean

      - name: Build Project (skip tests in CI)
        run: mvn package -DskipTests

      - name: Run Payroll Job
        shell: powershell
        run: |
          # Determine payroll month
          $payrollMonth = '${{ github.event.inputs.month }}'
          if ([string]::IsNullOrEmpty($payrollMonth)) {
              $payrollMonth = (Get-Date).ToString('MM')
          }
          Write-Host "Generating payroll for month: $payrollMonth"

          # Run Payroll job
          java -cp target/hrms_project-1.0-SNAPSHOT-shaded.jar com.hrms.model.service.PayrollJobs $payrollMonth > payroll.log 2>&1

      - name: Upload payroll log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: payroll-log
          path: payroll.log
