name: Qodana Code Quality

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  qodana:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run Qodana Scan
        uses: JetBrains/qodana-action@v2024.2
        with:
          cache-default-branch-only: true
