#-------------------------------------------------------------------------------#
#            Discover all capabilities of Qodana in our documentation           #
#             https://www.jetbrains.com/help/qodana/about-qodana.html           #
#-------------------------------------------------------------------------------#

name: Qodana

# Triggers
on:
  workflow_dispatch:       # Manual trigger
  pull_request:            # Trigger on PRs
  push:
    branches:
      - master             # Trigger on push to master

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0

      # Step 2: Run Qodana Scan
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          pr-mode: false                # Set to 'true' to check only changed files in PR
          use-caches: true
          post-pr-comment: true
          use-annotations: true
          upload-result: false          # Set 'true' if you want SARIF/artifacts uploaded
          push-fixes: 'none'           # Options: none, all, quick-fixes (Ultimate plans)
